const names = {
  VER: "Max Verstappen",
  PER: "Sergio Pérez",
  HAM: "Lewis Hamilton",
  RUS: "George Russell",
  LEC: "Charles Leclerc",
  SAI: "Carlos Sainz",
  NOR: "Lando Norris",
  PIA: "Oscar Piastri",
  ALO: "Fernando Alonso",
  STR: "Lance Stroll",
  OCO: "Esteban Ocon",
  GAS: "Pierre Gasly",
  ALB: "Alexander Albon",
  SAR: "Logan Sargeant",
  TSU: "Yuki Tsunoda",
  BOT: "Valtteri Bottas",
  ZHO: "Zhou Guanyu",
  MAG: "Kevin Magnussen",
  HUL: "Nico Hülkenberg",
  DEV: "Nyck de Vries",
  RIC: "Daniel Ricciardo",
  LAW: "Liam Lawson",
  MSC: "Mick Schumacher",
  LAT: "Nicholas Latifi",
};

export default names;